# Generated by Django 6.1 on 2026-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kyc', 'Bank / KYC'), ('electricity', 'Electricity Disconnection'), ('courier', 'Courier / Customs'), ('job', 'Job / Loan Offer'), ('government', 'Government Impersonation'), ('sextortion', 'Sextortion')], max_length=20)),
                ('template_text', models.TextField()),
                ('normalized_text', models.TextField()),
                ('sighting_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
