# Generated by Django 6.1 on 2026-08-31 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kyc', 'Bank / KYC'), ('electricity', 'Electricity Disconnection'), ('courier', 'Courier / Customs'), ('job', 'Job / Loan Offer'), ('government', 'Government Impersonation'), ('sextortion', 'Sextortion')], max_length=20)),
                ('template_text', models.TextField()),
                ('normalized_text', models.TextField()),
                ('sighting_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(max_length=2000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('score', models.IntegerField()),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('llm_explaination', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('reported', models.BooleanField(default=False)),
                ('matched_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='checker.scampattern')),
            ],
        ),
    ]
