# Generated by Django 6.1 on 2026-08-31 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='matched_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='dashboard.scampattern'),
        ),
        migrations.DeleteModel(
            name='ScamPattern',
        ),
    ]
