# Generated by Django 6.1.1 on 2026-09-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_alter_submission_matched_pattern_delete_scampattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='llm_explaination',
            new_name='llm_explanation',
        ),
    ]
